"""add dates for products

Revision ID: 8f9ec1fb14a5
Revises: 9b2fee6a096b
Create Date: 2026-05-06 10:22:28.986215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9ec1fb14a5'
down_revision: Union[str, Sequence[str], None] = '9b2fee6a096b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'replies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
