name: fastapi-ecommerce-prod

services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    env_file:
      - .env
    environment:
      - DB_HOST=db
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - media_data:/home/fast/media
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - VITE_YANDEX_MAPS_API_KEY=${VITE_YANDEX_MAPS_API_KEY}
        - VITE_OWNER_NAME=${VITE_OWNER_NAME}
        - VITE_OWNER_PHONE=${VITE_OWNER_PHONE}
        - VITE_OWNER_INN=${VITE_OWNER_INN}
    volumes:
      - media_data:/var/www/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email distortion616@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d 174-store.ru
    depends_on:
      - nginx

volumes:
  postgres_data:
  media_data:
